name: Dependency Review

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/package-lock.json'
      - '**/packages.config'
      - '**/*.csproj'
      - '**/*.fsproj'
      - '**/*.vbproj'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Dependency Review Action
        uses: github/dependency-review-action@v2